coki/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('coki_app.urls')),
]

coki_app/urls.py
from django.urls import path
from . import views

app_name = 'coki_app'

urlpatterns = [
    path( '' , views.index , name = 'index' ),
        # http://localhost:8000/6/smartphone-samsung-galaxy-s8-plus/
    path('<int:id>/<slug:slug_do_produto>/', views.exibe_produto, name='exibe_produto')
]

coki_app/models.py
from django.db import models
from django.urls import reverse

class Categoria(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        db_table='categoria'

    def get_absolute_path(self):
        return reverse('produto:lista_produtos_por_categoria', args=[self.slug])

    def __str__(self):
        return self.nome

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    imagem = models.CharField(max_length=200)
    descricao = models.TextField(blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    estoque = models.PositiveIntegerField()
    disponivel = models.BooleanField(default=True)
    likes = models.IntegerField('likes', default=0)
    dislikes = models.IntegerField('dislikes', default=0)

    class Meta:
        db_table = 'produto'

    def get_absolute_path(self):
        return reverse('produto:exibe_produto', args=[self.id, self.slug])

    def __str__(self):
        return self.nome

class FotoCarousel(models.Model):
    nome = models.CharField('nome', max_length=200, blank=True)
    endereco = models.CharField('Imagem', max_length=200)
    objects = models.Manager()

    class Meta:
        db_table = 'fotoCarousel'

    # def get_absolute_path(self):
    #     return reverse('estetica:facial')

    def __str__(self):
        return self.nome

class Foto(models.Model):
    nome = models.CharField('nome', max_length=200, blank=True)
    endereco = models.CharField('Foto', max_length=200)
    objects = models.Manager()

    class Meta:
        db_table = 'foto'

    def __str__(self):
        return self.nome

coki_app/views.py
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Categoria, Produto, FotoCarousel, Foto

def index(request):
   fotos_carousel = FotoCarousel.objects.all()
   fotos = Foto.objects.all()
   return render(request, 'coki_app/index.html', {'fotos_carousel': fotos_carousel, 'fotos': fotos})

def exibe_produto(request, id, slug_do_produto):
   produto = get_object_or_404(Produto, id=id)
   return render(request, 'coki_app/exibe.html', {'produto': produto})

'''
def lista_produtos(request, slug_da_categoria=None):
   categoria = None
   categorias = Categoria.objects.all().order_by("nome")
   produtos = Produto.objects.filter(disponivel=True).order_by("nome")
   if slug_da_categoria:
      categoria = get_object_or_404(Categoria, slug=slug_da_categoria)
      produtos = produtos.filter(categoria=categoria).order_by("nome")

   return render(request, 'coki_app/lista.html', {'categorias': categorias,
                                                 'produtos': produtos,
                                                 'categoria': categoria})
'''

coki_app/templates/coki_app/exibe.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Computador
{% endblock %}

{% block estilo %}
    <style>
        a {
            color: #337ab7;
        }
    </style>
{% endblock %}

{% block conteudo %}
   <div class="row">
      <div class="col-md-3 mb-3 mb-md-0">
         <!-- style="min-height: 150px; min-width: 150px;" -->
         <img class="img-fluid rounded" 
         src="{% static 'produto/imagens/' %}{{ produto.imagem }}">
      </div>
      <div class="col-md-9">
         <h4>{{ produto.nome }}</h4>
         <h5><a href="{{ produto.categoria.get_absolute_path }}">{{ produto.categoria }}</a></h5>
         <p>R$ {{ produto.preco }}</p>
         <p>{{ produto.descricao }}</p>
      </div>
   </div>
{% endblock %}

coki_app/templates/coki_app/helpPage.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="assets/css/bootstrap.css" rel="stylesheet">
	<link href="assets/css/all.css" rel="stylesheet">
	<link href="assets/css/styles.css" rel="stylesheet">
	<title>Coki</title>
</head>

<body>
	<nav class="fixed-top navbar navbar-dark bg-dark navbar-expand-md fixed-top">
		<div class="container-fluid">
			<div class="navbar-collapse collapse" id="categorias">
				<div class="navbar-nav mr-auto">
					<div class="dropdown">
						<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
							id="dropdownMasculino" href="#masculino">Masculino</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu">
							<a class="dropdown-item" href="productsPage.html">Calçados</a>
							<a class="dropdown-item" href="productsPage.html">Camisas</a>
							<a class="dropdown-item" href="productsPage.html">Calças</a>
							<a class="dropdown-item" href="productsPage.html">Relógios</a>
							<a class="dropdown-item" href="productsPage.html">Óculos</a>
						</div>
					</div>
					<div class="dropdown">
						<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
							id="dropdownFeminino" href="#feminino">Feminino</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu">
							<a class="dropdown-item" href="#calcados">Calçados</a>
							<a class="dropdown-item" href="#calcas">Camisas</a>
							<a class="dropdown-item" href="#oculos">Acessórios</a>
						</div>
					</div>
					<div class="dropdown">
						<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
							id="dropdownInfantil" href="#infantil">Infantil</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu">
							<a class="dropdown-item" href="#calcados">Calçados</a>
							<a class="dropdown-item" href="#calcas">Camisas</a>
							<a class="dropdown-item" href="#relogios">Moletons</a>
							<a class="dropdown-item" href="#oculos">Macacões</a>
						</div>
					</div>
					<div class="dropdown">
						<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
							id="dropdownInfantil" href="#esportes">Esportes</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenu">
							<a class="dropdown-item" href="#calcados">Calçados</a>
							<a class="dropdown-item" href="#calcas">Camisas de Futebol</a>
							<a class="dropdown-item" href="#relogios">Moletons</a>
							<a class="dropdown-item" href="#oculos">Shorts</a>
						</div>
					</div>
				</div>
				<div class="centralizar-horizontalmente centralizar-verticalmente">
					<a class="navbar-brand align-contentcenter" href="index.html">
						<img src="assets/images/Logo.png" style="width: 40px" alt="Coki">
					</a>
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#categorias"
						aria-controls="categorias" aria-expanded="false" aria-label="Coki">
						<span class="navbar-toggler-icon"></span>
					</button>
				</div>
				<div class="navbar-nav">
					<a class="nav-link nav-item" href="HelpPage.html">
						<i class="fas fa-question"></i> Ajuda
					</a>
					<a class="nav-link nav-item" href="#atendimento">
						<i class="fas fa-phone"></i> Atendimento
					</a>
					<a class="nav-link nav-item" href="loginPage.html">
						<i class="fas fa-user"></i> Entrar
					</a>
				</div>
			</div>
		</div>
	</nav>
	<!--Ajuda-->
	<div class="jumbotron jumbotron-fluid container" style="margin-top: 100px;">
		<div class="container">
			<h1 class="display-4">Quem Somos?</h1>
			<p class="lead">Somos uma loja virtual com pouco tempo de mercado mas apresentando um ótimo serviço levando
				até você o melhor da moda sem precisar sair do conforto de sua casa.</p>
		</div>
	</div>
	<div class="jumbotron jumbotron-fluid container">
		<div class="container">
			<h1 class="display-4">Dúvidas Frequentes</h1>
			<p class="lead">Existe garantia caso meu produto não chegue até mim?</p>
			<p class="lead">Sim. Existe garantia e a Coki garante a devolução da quantia em até 7 dias úteis após o
				relato do acontecimento.</p>
			<div style="margin-top: 10px;">
				<p class="lead">Quanto a demora da entrega. O que fazer se o pedido demorar mais do que o tempo
					estimado?</p>
				<p class="lead">Caso a entrega esteja atrasada, entre em contato conosco via email ou por nosso número
					de telefone que iremos procurar uma solução para o caso.</p>
			</div>
		</div>
	</div>
	<!-- Rodapé -->
	<div style="background-color: rgba(0,0,0,0.06); margin-left: 4px; margin-top: 20px; display: flex;">
		<div class="item-rodape">
			<h5 class="text-dark" style="margin-left: 22px;">Empresas Parceiras</h5>
			<ul>
				<li><i>Nestlé</i></li>
				<li>Bradesco</li>
				<li>Nubank</li>
				<li>Cielo</li>
			</ul>
		</div>

		<div class="item-rodape">
			<h5 class="text-dark" style="margin-left: 22px;">Estados</h5>
			<ul>
				<li>Rio de Janeiro</li>
				<li>São Paulo</li>
				<li>Minas Gerais</li>
				<li>Rondônia</li>
			</ul>
		</div>

		<div class="item-rodape">
			<h5 class="text-dark" style="margin-left: 22px;">Redes Sociais</h5>
			<ul>
				<li>Twitter</li>
				<li>Facebook</li>
				<li>Instagram</li>
				<li>Snapchat</li>
			</ul>
		</div>

		<div class="item-rodape">
			<h5 class="text-dark" style="margin-left: 22px;">Contato</h5>
			<ul>
				<li>Coki</li>
				<li>(11)99999-9999</li>
				<li>coki@gmail.com
				</li>
			</ul>
		</div>
	</div>

	<!--
   <header class="bgimage d-none d-md-block mb-4"></header>
-->
	<script src="assets/js/jquery-3.3.1.js"></script>
	<script src="assets/js/popper.js"></script>
	<script src="assets/js/bootstrap.js"></script>
	<script src="assets/js/script.js"></script>
</body>

</html>

coki_app/templates/coki_app/index.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
Home
{% endblock %}

{% block estilo %}
<style>
  .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
    color: #fff;
    background-color: #337ab7;
  }
  a.nav-link:hover {
    background-color: #eeeeee;
  }
  a {
    color: #337ab7;
  }
</style>
{% endblock estilo %}

{% block conteudo %}
{% static "images" as baseUrl %}
<header id="header" class="mb-4" style="margin-top: 120px;">
{% for foto in fotos %}
<img class="d-block w-100" src="src="{% static 'coki_app/images/' %}{{ foto.endereço }}">">
{% endfor %}


































<!--
   <div class="row">
      <div class="col-lg-3">
         <h3>Categorias</h3>
         <div class="nav flex-column nav-pills">
            <a class="nav-link {% if not categoria %}active{% endif %}" 
               href="/">Todos</a>
            {% for cat in categorias %}
               <a class="nav-link {% if cat == categoria %}active{% endif %}" 
                  href="{{ cat.get_absolute_path }}">
                  {{ cat.nome }}
               </a>
            {% endfor %}   
         </div>
      </div>

      <div class="col-lg-9">
         <h3>{% if not categoria %}Produtos{% else %}{{ categoria.nome }}{% endif %}</h3>
         <div class="row">
            {% for produto in produtos %}
               <div class="col-xl-4 col-lg-6">
                  <a href="{{ produto.get_absolute_path }}">
                     <img class="img-fluid rounded" height="220px" width="220px" 
                          src="{% static 'produto/imagens/' %}{{ produto.imagem }}">
                  </a>
                  <h5 class="mt-3" style="font-size: 16px">
                     <a href="{{ produto.get_absolute_path }}">
                        {{ produto.nome }}
                     </a>
                  </h5>
                  R$ {{ produto.preco }}
                  <br>
                  <br>
               </div>
            {% endfor %}
         </div>
      </div>
   </div>
 -->
 {% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="{% static 'coki_app/css/bootstrap.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'coki_app/css/all.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'coki_app/css/geral.css' %}"/>
	<title>{% block titulo %}Coki{% endblock titulo %}</title>
	<style>
		{% block estilo %}

		{% endblock estilo %}		
	</style>
</head>
<body>

<nav id= "barra-navegacao" class="fixed-top navbar navbar-dark bg-dark navbar-expand-md fixed-top">
	<div class="container">
		<div class="navbar-nav mr-auto">
			<div class="dropdown">
				<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
				id="dropdownMasculino" href="#masculino">Masculino</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenu">
					<a class="dropdown-item" href="{% url 'coki_app:index' %}">Calçados</a>
					<a class="dropdown-item" href="{% url 'coki_app:index' %}">Camisas</a>
					<a class="dropdown-item" href="{% url 'coki_app:index' %}">Calças</a>
					<a class="dropdown-item" href="{% url 'coki_app:index' %}">Relógios</a>
					<a class="dropdown-item" href="{% url 'coki_app:index' %}">Óculos</a>
				</div>
			</div>
			<div class="dropdown">
				<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
				id="dropdownFeminino" href="#feminino">Feminino</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenu">
					<a class="dropdown-item" href="#calcados">Calçados</a>
					<a class="dropdown-item" href="#calcas">Camisas</a>
					<a class="dropdown-item" href="#oculos">Acessórios</a>
				</div>
			</div>
			<div class="dropdown">
				<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
				id="dropdownInfantil" href="#infantil">Infantil</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenu">
					<a class="dropdown-item" href="#calcados">Calçados</a>
					<a class="dropdown-item" href="#calcas">Camisas</a>
					<a class="dropdown-item" href="#relogios">Moletons</a>
					<a class="dropdown-item" href="#oculos">Macacões</a>
				</div>
			</div>
			<div class="dropdown">
				<a class="btn nav-link nav-item dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
				id="dropdownInfantil" href="#esportes">Esportes</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenu">
					<a class="dropdown-item" href="#calcados">Calçados</a>
					<a class="dropdown-item" href="#calcas">Camisas de Futebol</a>
					<a class="dropdown-item" href="#relogios">Moletons</a>
					<a class="dropdown-item" href="#oculos">Shorts</a>
				</div>
			</div>
		</div>
		<div class="navbar-collapse collapse" id="categorias">
			<div class="navbar-brand mx-auto">
				<a class="" href="{% url 'coki_app:index' %}">
				<img src="{% static 'coki_app/images/Logo.png' %}" style="	width: 40px" alt="Coki">
				</a>
				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#categorias"
				aria-controls="categorias" aria-expanded="false" aria-label="Coki">
				<span class="navbar-toggler-icon"></span>
				</button>
			</div>
		</div>
		<div class="navbar-nav">
			<a class="nav-link nav-item" href="HelpPage.html">
				<i class="fas fa-question"></i> Ajuda
			</a>
			<a class="nav-link nav-item" href="#atendimento">
				<i class="fas fa-phone"></i> Atendimento
			</a>
			<a class="nav-link nav-item" href="loginPage.html">
				<i class="fas fa-user"></i> Entrar
			</a>
		</div>
	</div>
</nav>
<div>
	{% block conteudo %}

	{% endblock %}	
</div>
<!-- Rodapé -->
<div class="footer"> 
	<div class="container">
		<div class="shadow retangulo" style="background-color: rgba(0,0,0,0.06);">
			<div class="row">
				<div class="col-lg-3 col-sm-7">
					<div class="item-rodape">
						<h5 class="text-dark" style="margin-left: 22px;">Empresas Parceiras</h5>
						<ul>
							<li><i>Nestlé</i></li>
							<li>Bradesco</li>
							<li>Nubank</li>
							<li>Cielo</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-7">
					<div class="item-rodape">
						<h5 class="text-dark" style="margin-left: 22px;">Estados</h5>
						<ul>
							<li>Rio de Janeiro</li>
							<li>São Paulo</li>
							<li>Minas Gerais</li>
							<li>Rondônia</li>
						</ul>
					</div>
				</div>				
				<div class="col-lg-3 col-sm-7">
					<div class="item-rodape">
						<h5 class="text-dark" style="margin-left: 22px;">Redes Sociais</h5>
						<ul>
							<li>Twitter</li>
							<li>Facebook</li>
							<li>Instagram</li>
							<li>Snapchat</li>
						</ul>
					</div>
				</div>				
				<div class="col-lg-3 col-sm-7">
					<div class="item-rodape">
						<h5 class="text-dark" style="margin-left: 22px;">Contato</h5>
						<ul>
							<li>Coki</li>
							<li>(11)99999-9999</li>
							<li>coki@gmail.com</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Fim Rodapé -->
<script src="{% static 'coki_app/js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'coki_app/js/popper.js' %}"></script>
<script src="{% static 'coki_app/js/bootstrap.js' %}"></script>
<script src="{% static 'coki_app/js/script.js' %}"></script>
<script>
	$(document).ready(function () {
		{% block domready %}

		{% endblock %}
	});	
</script>
</body>
</html>